export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';

export const UPDATE_FIELD = 'UPDATE_FIELD';

export const UPDATE_SECURITY = 'UPDATE_SECURITY';